# Generated by Django 2.0.1 on 2018-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Multiview')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='http', max_length=4)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True)),
                ('port', models.SmallIntegerField(default='80')),
                ('name', models.TextField(blank=True, null=True)),
                ('broadcast_type', models.IntegerField(choices=[(0, 'IPTV'), (1, 'OTT'), (2, 'SAT')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='multiview',
            name='stream_list',
            field=models.ManyToManyField(related_name='stream_list', to='engine.Stream'),
        ),
    ]
